sudo: required
servers:
  - docker


before_install:
  - docker build -t arun-ramesh07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arun-ramesh07/react-test npm test -- --coverage

after_success:
  - docker build -t arun-ramesh07/multi-client ./client
  - docker build -t arun-ramesh07/multi-nginx ./nginx
  - docker build -t arun-ramesh07/multi-server ./server
  - docker build -t arun-ramesh07/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push arun-ramesh07/multi-client
  - docker push arun-ramesh07/multi-nginx
  - docker push arun-ramesh07/multi-server
  - docker push arun-ramesh07/multi-worker
