sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t arunramesh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arunramesh/react-test npm test

after_success:
  - docker build -t arunramesh/multi-client ./client
  - docker build -t arunramesh/multi-nginx ./nginx
  - docker build -t arunramesh/multi-server ./server
  - docker build -t arunramesh/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push arunramesh/multi-client
  - docker push arunramesh/multi-nginx
  - docker push arunramesh/multi-server
  - docker push arunramesh/multi-worker
